### ISSUE TITLE
审批的有计划吗？

### ISSUE THREAD

**Issue by lilos** [larksuite/oapi-sdk-go#20]
审批 event 有计划不？

**Comment by zhaoche27** [comment]
能提供一下 event 对应的文档地址吗？

**Comment by lilos** [comment]
https://open.feishu.cn/document/ukTMukTMukTM/uUTNxYjL1UTM24SN1EjN   有离职审批后触发清理内部系统账户操作需求

**Comment by zhaoche27** [comment]
有计划，打算月底可以生成api、event的SDK

**Comment by lilos** [comment]
参考其他模块实现了需要的接口先用着。
