### ISSUE TITLE
message/v4/send接口，成功发送消息，但是返回值报错

### ISSUE THREAD

**Issue by yang-ybb** [larksuite/oapi-sdk-go#31]
err = {
  Code: -1,
  Msg: "Post \"https://open.feishu.cn/open-apis/message/v4/send\": context canceled"
}

消息内容是一个卡片：{"elements":[{"tag":"div","text":{"content":"xxxxx","tag":"lark_md"}}],"header":{"template":"blue","title":{"content":"","tag":"plain_text"}}}

**Comment by zhaoche27** [comment]
context canceled， 应该是超时了吧

**Comment by zhaoche27** [comment]
你看看的context 有没有设置超时
