### ISSUE TITLE
机器人中能不能获取有效期比较长的 user_access_token

### ISSUE THREAD

**Issue by KevinGong2013** [larksuite/oapi-sdk-go#34]
比如我们计划用机器人自动维护一个多维表格，如果每次修改表格之前都需要有一个用户走认证去获取user_access_token, 那就变的一点都不自动了

**Comment by zhaoche27** [comment]
当前不行的，需要在user_access_token过期前，需要使用 refresh_access_token  获取新的user_access_token
https://open.feishu.cn/document/ukTMukTMukTM/uQDO4UjL0gDO14CN4gTN

**Comment by KevinGong2013** [comment]
有变通的办法，可以建一个群把机器人加进去，然后给这个群编辑云文档的权限。然后云文档的api就可以用tenant_access_token来调用。避免去获取user_access_token。
