### ISSUE TITLE
按照实例，获取不到部门列表

### ISSUE THREAD

**Issue by yrui319** [larksuite/oapi-sdk-go#35]
testDepartmentServiceList GoSDK 按照实例，获取不到部门列表

**Comment by zhaoche27** [comment]
你可以吧日志级别调成debug级别，看看日志中的url、request body ， response body 都有日志，看看与API文档的描述是否一致，如果是一致的，说明是业务问题（可以反馈给客服人员），不是SDK的问题。

**Comment by yrui319** [comment]
Dear 飞书SDK：
&nbsp; &nbsp; 感谢您能解答我的问题，请看我以下代码。










------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "larksuite/oapi-sdk-go"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月23日(星期三) 下午3:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [larksuite/oapi-sdk-go] 按照实例，获取不到部门列表 (#35)





 
你可以吧日志级别调成debug级别，看看日志中的url、request body ， response body 都有日志，看看与API文档的描述是否一致，如果是一致的，说明是业务问题（可以反馈给客服人员），不是SDK的问题。

**Comment by zhaoche27** [comment]
首先没有看到你的代码。
请按照我提供的问题来排查问题哈，可以最快的解决问题。其次我们的业务数据环境不一致，如果是业务问题，恐不能复现。

**Comment by yrui319** [comment]
Dear 飞书SDK：
&nbsp; &nbsp; 抱歉，直接把图片贴在邮件中无法查看，请请查看附件。


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "larksuite/oapi-sdk-go"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月23日(星期三) 下午3:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [larksuite/oapi-sdk-go] 按照实例，获取不到部门列表 (#35)





 
你可以吧日志级别调成debug级别，看看日志中的url、request body ， response body 都有日志，看看与API文档的描述是否一致，如果是一致的，说明是业务问题（可以反馈给客服人员），不是SDK的问题。

**Comment by yrui319** [comment]
我找到问题了，获取“部门信息列表”这个接口中，parent_department_id 这项参数是必须传的无值也要传个空，才能返回所有部门的信息，我已经在飞书开放平台提交了这项错误。
