### ISSUE TITLE
请问使用封装好的方法，返回的值应该用什么方式接呢 Golang？

### ISSUE THREAD

**Issue by yrui319** [larksuite/oapi-sdk-go#36]
例如：testDepartmentServiceList 方法Do()后，返回的是 *DepartmentListResult 类型，如何传为json对象？或如何直接映射到自定义的结构体呢？

**Comment by zhaoche27** [comment]
为啥要定义自己的结构体，*DepartmentListResult 类型 有什么不足吗？
