### ISSUE TITLE
Request 不能订阅审批事件

### ISSUE THREAD

**Issue by KevinGong2013** [larksuite/oapi-sdk-go#37]
审批的HTTP URL是这个：https://www.feishu.cn/approval/openapi/v2/subscription/subscribe

Request的url是这个：
<img width="1168" alt="Screen Shot 2021-07-03 at 11 32 26" src="https://user-images.githubusercontent.com/5820203/124341921-9eef8d00-dbf2-11eb-945a-1384e607c752.png">

这个OAPIRootPath 不一致

**Comment by zhaoche27** [comment]
是的，后面会修改SDK，来兼容这个逻辑。

**Comment by zhaoche27** [comment]
go get github.com/larksuite/oapi-sdk-go@support_helpdesk  

这个support_helpdesk分支的 Url 方法调整了，支持 url 全路径。 你可以先用着，后面会 merge 到主分支。

**Comment by KevinGong2013** [comment]
字节的速度可以的👍
