### ISSUE TITLE
下载图片示例缺少参数

### ISSUE THREAD

**Issue by KevinGong2013** [larksuite/oapi-sdk-go#41]
[下载文件](https://github.com/larksuite/oapi-sdk-go/blob/fb362baae4284ce15cc40493f669e19d388caa8b/sample/api/api.go#L132)的示例调用的时候会报错，提示参数错误。

<img width="415" alt="Screen Shot 2021-07-13 at 12 42 31" src="https://user-images.githubusercontent.com/5820203/125391908-cbb45900-e3d7-11eb-8101-593d241931c3.png">

需要在这个参数里加上`operator`。 像这样 `request.SetQueryParams(map[string]interface{}{"image_key": imageKey, "operator": "app"}) `

**Comment by zhaoche27** [comment]
没看明白，能详细的说一下吗？

**Comment by KevinGong2013** [comment]
@zhaoche27 我编辑了下

**Comment by zhaoche27** [comment]
https://open.feishu.cn/document/ukTMukTMukTM/uYzN5QjL2cTO04iN3kDN 从文档上看，不需要 operator 参数

**Comment by zhaoche27** [comment]
可以复现，找到问题了，谢谢你的反馈，已经把问题反馈给API的开发者。

**Comment by KevinGong2013** [comment]
> https://open.feishu.cn/document/ukTMukTMukTM/uYzN5QjL2cTO04iN3kDN 从文档上看，不需要 operator 参数

嗯的确， 但是我加一个operator=app 就可以获取到了，在小程序中获取图片的链接是这样子的

` https://open.feishu.cn/open-apis/image/v4/get?imag%E2%80%A6ada5f1de-6ec5-41f1-ae42-7ac0d46172dg&operator=app `

**Comment by zhaoche27** [comment]
你从那里知道 需要添加 &operator=app 的？

**Comment by KevinGong2013** [comment]
> 你从那里知道 需要添加 &operator=app 的？

消息扩展， 小程序中获取图片消息地址带了这个参数

**Comment by zhaoche27** [comment]
能给一下 文档的URL吗？
