### ISSUE TITLE
请教使用gin框架，用何种正确姿势的食用方法！跪求大佬！

### ISSUE THREAD

**Issue by yrui319** [larksuite/oapi-sdk-go#42]
Log级别为Debug

代码如下：
//飞书中EncryptKey为空
AppSet := config.NewInternalAppSettings(AppID, AppSecret, Verification, Encrypt)
FeiShuConf = config.NewConfigWithDefaultStore(constants.DomainFeiShu, AppSet, log.NewDefaultLogger(), log.LevelDebug)

func Event(ctx *gin.Context)  {

	im.SetMessageReceiveEventHandler(FeiShuConf, func(ctx *core.Context, event *im.MessageReceiveEvent) error {
		fmt.Println("**************** SetMessageReceiveEventHandler ****************")
		fmt.Println("GetID: ", ctx.GetRequestID())
		fmt.Println("SetMessageReceiveEventHandler", tools.Prettify(event))
		return nil
	})
	eventhttp.Handle(FeiShuConf, ctx.Request, ctx.Writer)
}

请问如何拿到 event？或 直接在 im.SetMessageReceiveEventHandler中使用？
获取event内数据只能通过tools.Prettify(event.Event)吗？

**Comment by zhaoche27** [comment]
直接在  im.SetMessageReceiveEventHandler中使用， 你可以看看源代码 tools.Prettify()， 就是有格式的输出，与 fmt.Println() 类似。

**Comment by yrui319** [comment]
感谢！
