### ISSUE TITLE
复制和删除在线sheet文件有bug

### ISSUE THREAD

**Issue by linhuaqing0928** [larksuite/oapi-sdk-go#47]
service/drive_explorer/v2/api.go文件中。
1、无法使用AccessTokenTypeTenant
2、path多了/open-apis/

**Comment by zhaoche27** [comment]
谢谢反馈，我来处理一下

**Comment by zhaoche27** [comment]
1，我看了你的 pull request，该 API 支持 user_access_token\tenant_access_token 两种
2，path多了/open-apis/ ，可以看看源代码，做了兼容。

**Comment by linhuaqing0928** [comment]
1、嗯 应该是支持2种的
2、[Debug] [[unmarshalResponse] request:POST /open-apis//open-apis/drive/explorer/v2/file/copy/files/shtcn4XjVcK6FLAGVYDDSRgzhnJ tenant_access_token, response:body:{"code":99991201,"msg":"resource not find"}] 日志打印是有问题的呀 我找时间看下源码吧 用起来确实是有问题的

**Comment by zhaoche27** [comment]
你是用的SDK版本是？ 我这边测试是OK。 不会多 /open-apis/ 路径

**Comment by zhaoche27** [comment]
明天上午发布一版，修复 无法使用AccessTokenTypeTenant 的问题
