### ISSUE TITLE
SetTypeHandler时报concurrent map writes错误

### ISSUE THREAD

**Issue by Bigmonstercai** [larksuite/oapi-sdk-go#49]
![image](https://user-images.githubusercontent.com/7385523/131280463-0b9f393f-0f73-4fcf-abb8-7021551a90ff.png)

**Comment by zhaoche27** [comment]
存在并发了，当前使用map来存储 event type 与 handler 的对应关系，建议在 init() 完成 event type 与 handler 的对应关系
