### ISSUE TITLE
这个项目根本没有覆盖botframework-go的功能

### ISSUE THREAD

**Issue by zbw0046** [larksuite/oapi-sdk-go#5]
之前用botframework-go开发机器人，有很多封装好的方法可用。看到文档说deprecated redirect到这里，发现啥也没有…… 这让用户如何迁移啊

**Comment by zhaoche27** [comment]
看一下readme。有些方法oapi-sdk没有，可以使用原生的方式，陆续会有相应的业务api的sdk上线。

**Comment by zhaoche27** [comment]
本项目重新设计，
1，api、event、card模块
2，自动生成业务SDK，随着业务SDK的生成，从长期来看，功能更新强大。
