### ISSUE TITLE
获取不到 departments 部门列表

### ISSUE THREAD

**Issue by yrui319** [larksuite/oapi-sdk-go#51]
按照SDK+飞书服务端文档规定访问无法获取到部门列表
用POSTMAN脚本可以获取到

怀疑 "parent_department_id": "", 传送写的不对。请问应该怎么传空？

func GetDepartments()  {

	body := map[string]interface{}{
		"user_id_type": "open_id",
		"department_id_type": "open_department_id",
		"parent_department_id": "",
		"fetch_child":true,
		//"page_token":"",
		//"page_size":50,
	}

	//接收返回
	ret := make(map[string]interface{})

        //构建访问
	req := request.NewRequestWithNative("/open-apis/contact/v3/departments", "GET", request.AccessTokenTypeTenant, body, &ret)

	//上下文
	coreCtx := core.WrapContext(context.Background())

        //发送数据
	err := api.Send(coreCtx, FeiShuConf, req)
	if err != nil{
		e := err.(*response.Error)
		fmt.Println("发送给自己错误：", e, tools.Prettify(err))
		return
	}
	fmt.Println("发送给自己：", tools.Prettify(ret))
}

返回：
发送给自己： {
  has_more: false,
  items: [map[department_id:0 member_count:190 name: open_department_id:0]]
}

**Comment by zhaoche27** [comment]
这应该是一个 POST 请求吧。 你写的是  "GET",

**Comment by yrui319** [comment]
> 这应该是一个 POST 请求吧。 你写的是 "GET",

获取部门列表写的是GET方式
[image](https://user-images.githubusercontent.com/15337326/134451552-18c9cb4e-4004-4136-91fb-61c9005b35fd.png)

**Comment by zhaoche27** [comment]
你的代码写错了， query 参数，不是 request body。 get请求不应该有body。 你可以再看看 readme ，有说明 query 参数怎么传递的。

**Comment by yrui319** [comment]
> 你的代码写错了， query 参数，不是 request body。 get请求不应该有body。 你可以再看看 readme ，有说明 query 参数怎么传递的。

哇。。。感谢，已经搞定了~
