### ISSUE TITLE
MessageCardEmbedSelectMenuStatic.MarshalJSON() only returned 'tag'

### ISSUE THREAD

**Issue by mxlxm** [larksuite/oapi-sdk-go#57]
```
package main

import (
	"fmt"
	"github.com/larksuite/oapi-sdk-go/v2"
)

func main() {
	card := lark.MessageCard{
		Header: &lark.MessageCardHeader{
			Title:    &lark.MessageCardPlainText{Content: "k8s ticket"},
			Template: lark.StringPtr("indigo"),
		},
	}
	element := &lark.MessageCardAction{}
	cluster := &lark.MessageCardEmbedSelectMenuStatic{
		&lark.MessageCardEmbedSelectMenuBase{
			Placeholder: &lark.MessageCardPlainText{
				Content: "choose cluster",
			},
			InitialOption: "dev",
		},
	}
	element.Actions = append(element.Actions, cluster)
	card.Elements = append(card.Elements, element)
	content, err := card.JSON()
	if err != nil {
		fmt.Println(err)
	}
	fmt.Printf("card:%s\n", content)
}
```

out:
`card:{"header":{"template":"indigo","title":{"content":"k8s ticket","tag":"plain_text"}},"elements":[{"actions":[{"tag":"select_static"}],"tag":"action"}]}`

Embedded struct without json tag would be ignored at https://github.com/larksuite/oapi-sdk-go/blob/8e772c1740739bbb4d671cbff3b6d37373271d73/v2/utils.go#L311

**Comment by zhaoche27** [comment]
使用 github.com/larksuite/oapi-sdk-go/v2 v2.0.7

**Comment by zhaoche27** [comment]
card:{"header":{"template":"indigo","title":{"content":"k8s ticket","tag":"plain_text"}},"elements":[{"actions":[{"initial_option":"dev","placeholder":{"content":"choose cluster","tag":"plain_text"},"tag":"select_static"}],"tag":"action"}]}
