### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by mxlxm** [larksuite/oapi-sdk-go#58]
https://github.com/larksuite/oapi-sdk-go/blob/581d03b31523ca3c014ba03e066eb6846d9befe9/v2/message_model.go#L560
 
MessageCardActionLayoutDisected -> MessageCardActionLayoutBisected

**Comment by zhaoche27** [comment]
升级到  v2.0.9 ，谢谢反馈

**Comment by zhaoche27** [comment]
@mxlxm 如果你是bytedance的同学，你可以飞书一下我，我有些问题需要与你交流一下哈。

**Comment by mxlxm** [comment]
不是哈 只是用户
